# ---------------- #
#   Main Configs   #
# ---------------- #
url: https://github.lwlinux.cn
cdn: //ali-cdn.lwlinux.cn
date_format: "ordinal"
title: William A
keywords: William A, lwlwilliam
encoding: utf-8
side_bar_repo_limit: 0

about: Just for fun.
description: Love sports, love programming, love life.

# ---------------- #
#      Author      #
# ---------------- #
author: lwlwilliam
location: Guangzhou, China
email: lwlwilliam@foxmail.com
repository: lwlwilliam.github.io
repository_url: https://github.com/lwlwilliam/lwlwilliam.github.io
avatar: https://avatars1.githubusercontent.com/u/25366940?s=150&v=4

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: Home

  -
    href: /categories/
    label: Catetories

  -
    href: /archives/
    label: Archieves

  - href: /books/
    label: Books

  -
    href: /links/
    label: Links

#  -
#    href: /wiki/
#    label: Wiki

  -
    href: /about/
    label: About

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 5
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
    - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#     Comments     #
# ---------------- #
comments_provider: gitalk
gitalk:
    clientID: ef26baa975fbac82ac52
    clientSecret: 2ccf1fb00dbced9773c1fa27252534d28af38986
