# 个人信息
title: William A
email: lwlwilliam.a@gmail.com
github_username: lwlwilliam
description: Love sports, love programming, love life.

# 页面配置
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
paginate: 5
paginate_path: "page:num"
