baseURL = 'https://pages.lwlinux.cn/'
publishDir = "docs"
languageCode = 'zh-cn'
title = 'William A'

[params]
  keywords = 'William A'
  encoding = 'utf-8'
  about = 'Just for fun.'
  description = 'Love sports, love programming, love life.'

  author = 'William A'

  paginate = 5
  paginationWindow = 2
  excerptLength = 150
  dateFormat = '2006-01-02'

  [[params.navs]]
    href = '/'
    label = 'cd ~'

  [[params.navs]]
    href = '/categories/'
    label = 'Categories'

  [[params.navs]]
    href = '/archives/'
    label = 'Archives'

  [[params.navs]]
    href = '/books/'
    label = 'Books'

  [[params.navs]]
    href = '/links/'
    label = 'Links'

  [[params.navs]]
    href = '/tools/'
    label = 'Tools'

  [[params.navs]]
    href = '/todo/'
    label = 'Todo'

  [[params.navs]]
    href = '/about/'
    label = 'About'

[taxonomies]
  category = 'categories'

[outputs]
  home = ['HTML', 'RSS', 'SearchJSON']
  page = ['HTML']
  section = ['HTML']
  taxonomy = ['HTML']
  term = ['HTML']

[outputFormats]
  [outputFormats.RSS]
    baseName = 'feed'
  [outputFormats.SearchJSON]
    mediaType = 'application/json'
    baseName = 'search'
    isPlainText = true
    notAlternative = true

[services]
  [services.rss]
    limit = 20

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['$$', '$$'], ['\\[', '\\]']]
          inline = [['$', '$'], ['\\(', '\\)']]

  [markup.highlight]
    style = 'monokai'

[permalinks]
  posts = '/:year/:month/:day/:slug/'
